[project]
name = 'Sustainable-Tourism-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.booking-integration]
path = 'contracts/booking-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.eco-certification]
path = 'contracts/eco-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.reward-distribution]
path = 'contracts/reward-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
